name = "CellLists"
uuid = "b6871879-622e-446c-84f2-629b119ba541"
authors = ["Jaan Tollander de Balsch <jaan@hey.com>"]
version = "0.1.0"

[compat]
julia = "^1.3"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Random", "Test"]
